### ISSUE TITLE
Gcloud config set project VALUE fails as VALUE comes back empty

### ISSUE THREAD

**Issue by B-0-B-B-Y** [CircleCI-Public/gcp-cli-orb#29]
### Orb version
2.1.0

### What happened

Init job is failing when trying to substitute environment variables. Snippet of code where this is happening:

```
        # Store service account
        echo $<<parameters.gcloud-service-key>> > ${HOME}/gcloud-service-key.json
        # Initialize gcloud CLI
        gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
        gcloud --quiet config set project $<<parameters.google-project-id>>
        if [[ -n $<<parameters.google-compute-zone>> ]]; then
          gcloud --quiet config set compute/zone $<<parameters.google-compute-zone>>
        elif [[ -n $<<parameters.google-compute-region>> ]]; then
          gcloud --quiet config set compute/region $<<parameters.google-compute-region>>
        else
          echo "ERROR: Set <<parameters.google-compute-zone>> or <<parameters.google-compute-region>> env variable" >&2
          exit 1
        fi
```

Specifically at this line:

`gcloud --quiet config set project $<<parameters.google-project-id>>`

CircleCI output is as follows:

```
Activated service account credentials for: [redacted]


Updates are available for some Cloud SDK components.  To install them,
please run:
  $ gcloud components update

ERROR: (gcloud.config.set) argument VALUE: Must be specified.
Usage: gcloud config set SECTION/PROPERTY VALUE [optional flags]
  optional flags may be  --help | --installation

For detailed information on this command and its flags, run:
  gcloud config set --help

Exited with code exit status 2
```
Should the variable substitution for the parameters not be defined like this instead:

`${<< parameter.google-project-id >>}` , which circle will then actually read in from the project defined env variables?

Job which runs this command has parameters defined as such:

``` 
parameters:
      gcp-service-key:
        type: env_var_name
        default: GCLOUD_SERVICE_KEY_D1
      gcp-project-id:
        type: env_var_name
        default: GCLOUD_PROJECT_ID_D1
      gcp-storage:
        type: env_var_name
        default: GOOGLE_STORAGE_D1
```

and the orb command is invoked like this:

```
...
steps:
  - gcp-cli/install
  - gcp-cli/initialize:
      gcloud-service-key: << parameters.gcp-service-key >>
      google-project-id: << parameters.gcp-project-id >>
...
```

### Expected behavior

The substituion of variables passed into the orb command should not be null but rather contain the value of the specified in the project settings env variable, meaning when `gcloud --quiet config set project $<<parameters.google-project-id>>` is invoked, `$<<parameters.google-project-id>>` doesn't come back empty.
