### ISSUE TITLE
Google Cloud SDK is Unavailable

### ISSUE THREAD

**Issue by catherine-swift** [CircleCI-Public/gcp-cli-orb#87]
## What happened:
An outage at `https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/` has caused the Cloud SDK to not be available, thereby breaking any jobs that need to install it in order to use the GCP CLI.

https://app.circleci.com/pipelines/github/swift-school/swift/3174/workflows/1b6adbfb-c89a-42c3-99f1-6821bc1618d1/jobs/14961

## Expected behavior:

The Google Cloud SDK should be cached locally to Circle and the cached copy should be referenced by this orb so that outages at Google don't affect CircleCI services.  This might be a good time to update the client revision, too -- 293 is significantly older than 383.

**Comment by david-montano-circleci** [comment]
Users can use `restore_cache` and `save_cache` to cache the previously installed `gcloud` binary. The following yml file can be used as an example:
```yml
    steps:
      - restore_cache:
          key: gcp-cli
      - run:
          name: Find installed gcloud
          command: |
            INSTALL_TMP_DIR=$(find /tmp/tmp.* -iname path.bash.inc | cut -d'/' -f3)
            printf '%s\n' ". /tmp/${INSTALL_TMP_DIR}/google-cloud-sdk/path.bash.inc" >> ~/.bashrc
            printf '%s\n' ". /tmp/${INSTALL_TMP_DIR}/google-cloud-sdk/path.bash.inc" >> "$BASH_ENV"
            printf '%s\n' "export PATH=$PATH:/tmp/${INSTALL_TMP_DIR}/google-cloud-sdk/bin" >> ~/.profile
      - gcp-cli/install
      - save_cache:
          key: gcp-cli
          paths:
            - /tmp
```
Currently the `gcp-cli` installs `gcloud` in a temporary directory whose name is unknown. So in order to export it we have to run the logic in `Find installed gcloud`. As you can see this is not very intuitive.

It is true that we can add this logic to the orb as a new parameter. But this can be said to any other binary supported by CircleCI orbs.

Another solution is to run the pipeline in a docker container that contains the expected `gcloud` version pre installed.
